import { Header } from "@/components"



export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}


export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<>
			<Header isInputVisible={false} />
			{children}
		</>
	)
}
