import { Header } from '@/components/header'
import { Montserrat } from 'next/font/google'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

const montserrat = Montserrat({
	subsets: ['latin'],
	variable: '--font-montserrat',
	weight: ['400', '500', '600', '700', '800', '900'],
})

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<>
			<Header isInputVisible={true}></Header>
			{children}
		</>
	)
}
